use sqltype::analyzer::analyze_query;
use sqltype::catalog::Catalog;
use sqltype::codegen::generate_file_ts;
use std::fs;

#[test]
fn test_end_to_end_compiler_pipeline() {
    let base_dir = std::env::temp_dir().join(format!(
        "sqltype_e2e_{}",
        std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap()
            .as_nanos()
    ));

    let migrations_dir = base_dir.join("migrations");
    let queries_dir = base_dir.join("queries");
    let out_dir = base_dir.join("out");

    fs::create_dir_all(&migrations_dir).unwrap();
    fs::create_dir_all(&queries_dir).unwrap();
    fs::create_dir_all(&out_dir).unwrap();

    // 1. Setup deterministic sequential migrations
    fs::write(
        migrations_dir.join("001_init.sql"),
        r#"
        CREATE TABLE users (
            id UUID PRIMARY KEY,
            email TEXT NOT NULL,
            first_name VARCHAR(50),
            created_at TIMESTAMPTZ NOT NULL
        );

        CREATE TABLE posts (
            id UUID PRIMARY KEY,
            user_id UUID NOT NULL,
            title VARCHAR(255) NOT NULL,
            views INT NOT NULL DEFAULT 0,
            published BOOLEAN NOT NULL DEFAULT false
        );
        "#,
    )
    .unwrap();

    fs::write(
        migrations_dir.join("002_comments_and_alters.sql"),
        r#"
        CREATE TABLE comments (
            id UUID PRIMARY KEY,
            post_id UUID NOT NULL,
            body TEXT NOT NULL
        );

        ALTER TABLE users ADD COLUMN age INT;
        ALTER TABLE users ALTER COLUMN first_name SET NOT NULL;
        "#,
    )
    .unwrap();

    // 2. Setup query files
    let query_get_user = r#"
-- name: GetUserWithPosts
SELECT 
  u.id, 
  u.email, 
  p.title AS post_title,
  COUNT(c.id) AS comment_count
FROM users u
LEFT JOIN posts p ON p.user_id = u.id
LEFT JOIN comments c ON c.post_id = p.id
WHERE u.id = $1
GROUP BY u.id, u.email, p.title;
    "#;
    fs::write(queries_dir.join("get_user_with_posts.sql"), query_get_user).unwrap();

    let query_posts_by_status = r#"
-- name: FindPostsByStatus
SELECT 
  p.id,
  p.title,
  p.views,
  p.published
FROM posts p
WHERE p.published = $1;
    "#;
    fs::write(queries_dir.join("find_posts_by_status.sql"), query_posts_by_status).unwrap();

    // 3. Build in-memory schema catalog
    let catalog = Catalog::load_from_dir(&migrations_dir).expect("Failed to load catalog");

    // Verify catalog state
    let users_table = catalog.get_table("users").expect("users table should exist");
    assert_eq!(users_table.columns.len(), 5);
    assert!(!users_table.get_column("id").unwrap().is_nullable);
    assert!(!users_table.get_column("email").unwrap().is_nullable);
    assert!(!users_table.get_column("first_name").unwrap().is_nullable);
    assert!(users_table.get_column("age").unwrap().is_nullable);

    // 4. Analyze queries
    let analyzed_user = analyze_query(query_get_user, &catalog, Some("get_user_with_posts.sql")).unwrap();
    assert_eq!(analyzed_user.name, "GetUserWithPosts");
    assert_eq!(analyzed_user.params.len(), 1);
    assert_eq!(analyzed_user.params[0].name, "id");
    assert_eq!(analyzed_user.params[0].ts_type, "string");

    assert_eq!(analyzed_user.fields.len(), 4);
    assert_eq!(analyzed_user.fields[0].name, "id");
    assert_eq!(analyzed_user.fields[0].ts_type, "string");
    assert_eq!(analyzed_user.fields[1].name, "email");
    assert_eq!(analyzed_user.fields[1].ts_type, "string");
    assert_eq!(analyzed_user.fields[2].name, "post_title");
    assert_eq!(analyzed_user.fields[2].ts_type, "string | null");
    assert_eq!(analyzed_user.fields[3].name, "comment_count");
    assert_eq!(analyzed_user.fields[3].ts_type, "number");

    let analyzed_posts = analyze_query(query_posts_by_status, &catalog, Some("find_posts_by_status.sql")).unwrap();
    assert_eq!(analyzed_posts.name, "FindPostsByStatus");
    assert_eq!(analyzed_posts.params.len(), 1);
    assert_eq!(analyzed_posts.params[0].name, "published");
    assert_eq!(analyzed_posts.params[0].ts_type, "boolean");

    // 5. Code generation
    let ts_user = generate_file_ts(&[analyzed_user]);
    let out_file_user = out_dir.join("get_user_with_posts.ts");
    fs::write(&out_file_user, &ts_user).unwrap();

    let ts_posts = generate_file_ts(&[analyzed_posts]);
    let out_file_posts = out_dir.join("find_posts_by_status.ts");
    fs::write(&out_file_posts, &ts_posts).unwrap();

    // Verify generated TypeScript file contents
    assert!(ts_user.contains("// Autogenerated by sqltype. DO NOT EDIT."));
    assert!(ts_user.contains("export interface GetUserWithPostsParams {\n  id: string;\n}"));
    assert!(ts_user.contains("export interface GetUserWithPostsRow {\n  id: string;\n  email: string;\n  post_title: string | null;\n  comment_count: number;\n}"));
    assert!(ts_user.contains("export const getUserWithPostsSql = `"));
    assert!(ts_user.contains("export type GetUserWithPostsQuery = {\n  sql: string;\n  params: GetUserWithPostsParams;\n  row: GetUserWithPostsRow;\n};"));

    assert!(ts_posts.contains("export interface FindPostsByStatusParams {\n  published: boolean;\n}"));
    assert!(ts_posts.contains("export interface FindPostsByStatusRow {\n  id: string;\n  title: string;\n  views: number;\n  published: boolean;\n}"));
    assert!(ts_posts.contains("export const findPostsByStatusSql = `"));
    assert!(ts_posts.contains("export type FindPostsByStatusQuery = {\n  sql: string;\n  params: FindPostsByStatusParams;\n  row: FindPostsByStatusRow;\n};"));

    // 6. Test invalid query detection
    let bad_query = "SELECT nonexistent FROM users;";
    assert!(analyze_query(bad_query, &catalog, None).is_err());

    let _ = fs::remove_dir_all(base_dir);
}

#[test]
fn test_cte_and_expressions_integration() {
    let base_dir = std::env::temp_dir().join(format!(
        "sqltype_cte_e2e_{}",
        std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap()
            .as_nanos()
    ));

    let migrations_dir = base_dir.join("migrations");
    let queries_dir = base_dir.join("queries");
    let out_dir = base_dir.join("out");

    fs::create_dir_all(&migrations_dir).unwrap();
    fs::create_dir_all(&queries_dir).unwrap();
    fs::create_dir_all(&out_dir).unwrap();

    fs::write(
        migrations_dir.join("001_init.sql"),
        r#"
        CREATE TABLE users (
            id UUID PRIMARY KEY,
            email TEXT NOT NULL,
            age INT NOT NULL,
            nickname TEXT,
            active BOOLEAN NOT NULL
        );
        CREATE TABLE posts (
            id UUID PRIMARY KEY,
            user_id UUID NOT NULL,
            title VARCHAR(255) NOT NULL
        );
        "#,
    ).unwrap();

    let query_cte = r#"
-- name: GetActiveUsersWithPosts
WITH active_users AS (
    SELECT id, email, age, nickname FROM users WHERE active = true
)
SELECT 
    au.email,
    (au.age + 1) AS next_age,
    COALESCE(au.nickname, 'anon') AS display_name,
    p.title
FROM active_users au
JOIN posts p ON p.user_id = au.id;
    "#;
    fs::write(queries_dir.join("active_users.sql"), query_cte).unwrap();

    let catalog = Catalog::load_from_dir(&migrations_dir).unwrap();
    let analyzed = analyze_query(query_cte, &catalog, Some("active_users.sql")).unwrap();

    assert_eq!(analyzed.fields.len(), 4);
    assert_eq!(analyzed.fields[0].name, "email");
    assert_eq!(analyzed.fields[0].ts_type, "string");
    assert_eq!(analyzed.fields[1].name, "next_age");
    assert_eq!(analyzed.fields[1].ts_type, "number");
    assert_eq!(analyzed.fields[2].name, "display_name");
    assert_eq!(analyzed.fields[2].ts_type, "string");
    assert_eq!(analyzed.fields[3].name, "title");
    assert_eq!(analyzed.fields[3].ts_type, "string");

    let ts = generate_file_ts(&[analyzed]);
    assert!(ts.contains("email: string;"));
    assert!(ts.contains("next_age: number;"));
    assert!(ts.contains("display_name: string;"));
    assert!(ts.contains("title: string;"));

    let _ = fs::remove_dir_all(base_dir);
}
