use crate::analyzer::AnalyzedQuery;

/// Converts PascalCase or general string to camelCase.
pub fn to_camel_case(s: &str) -> String {
    let mut chars = s.chars();
    match chars.next() {
        None => String::new(),
        Some(first) => {
            let mut result = first.to_lowercase().to_string();
            result.extend(chars);
            result
        }
    }
}

/// Checks if a string is a valid JavaScript / TypeScript identifier.
fn is_valid_js_identifier(name: &str) -> bool {
    if name.is_empty() {
        return false;
    }
    let mut chars = name.chars();
    let first = chars.next().unwrap();
    if !first.is_alphabetic() && first != '_' && first != '$' {
        return false;
    }
    chars.all(|c| c.is_alphanumeric() || c == '_' || c == '$')
}

fn format_property_key(name: &str) -> String {
    if is_valid_js_identifier(name) {
        name.to_string()
    } else {
        format!("\"{}\"", name.replace('"', "\\\""))
    }
}

fn sanitize_sql_template(sql: &str) -> String {
    // Strip leading comment lines like '-- name: ...' and leading empty lines
    let mut content_lines = Vec::new();
    let mut skipping_leading = true;

    for line in sql.lines() {
        let trimmed = line.trim();
        if skipping_leading {
            if trimmed.is_empty() || trimmed.starts_with("--") {
                continue;
            }
            skipping_leading = false;
        }
        content_lines.push(line);
    }

    let joined = content_lines.join("\n");
    // Escape backticks and ${} template expressions
    joined
        .replace('`', "\\`")
        .replace("${", "\\${")
}

/// Generates TypeScript code for a single analyzed query.
pub fn generate_query_ts(query: &AnalyzedQuery) -> String {
    let name = &query.name;
    let camel_name = to_camel_case(name);
    let sql_const_name = format!("{}Sql", camel_name);

    let mut out = String::new();

    // 1. Params Interface
    out.push_str(&format!("export interface {}Params {{\n", name));
    for param in &query.params {
        let key = format_property_key(&param.name);
        if param.is_optional {
            let ts_type = if param.ts_type.contains("| null") {
                param.ts_type.clone()
            } else {
                format!("{} | null", param.ts_type)
            };
            out.push_str(&format!("  {}?: {};\n", key, ts_type));
        } else {
            out.push_str(&format!("  {}: {};\n", key, param.ts_type));
        }
    }
    out.push_str("}\n\n");

    // 2. Row Interface
    out.push_str(&format!("export interface {}Row {{\n", name));
    for field in &query.fields {
        let key = format_property_key(&field.name);
        out.push_str(&format!("  {}: {};\n", key, field.ts_type));
    }
    out.push_str("}\n\n");

    // 3. SQL string constant
    let clean_sql = sanitize_sql_template(&query.raw_sql);
    let clean_sql_trimmed = clean_sql.trim();
    out.push_str(&format!(
        "export const {} = `\n  {}\n`;\n\n",
        sql_const_name,
        clean_sql_trimmed.lines().collect::<Vec<_>>().join("\n  ")
    ));

    // 4. Query Type
    out.push_str(&format!("export type {}Query = {{\n", name));
    out.push_str("  sql: string;\n");
    out.push_str(&format!("  params: {}Params;\n", name));
    out.push_str(&format!("  row: {}Row;\n", name));
    out.push_str("};\n");

    out
}

/// Generates a complete TypeScript file for one or more analyzed queries.
pub fn generate_file_ts(queries: &[AnalyzedQuery]) -> String {
    let mut out = String::new();
    out.push_str("// Autogenerated by sqltype. DO NOT EDIT.\n\n");

    for (i, query) in queries.iter().enumerate() {
        if i > 0 {
            out.push('\n');
        }
        out.push_str(&generate_query_ts(query));
    }

    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::analyzer::{QueryField, QueryParam};

    #[test]
    fn test_codegen_matches_prompt_spec() {
        let query = AnalyzedQuery {
            name: "GetUserWithPosts".to_string(),
            raw_sql: "
-- name: GetUserWithPosts
SELECT 
  u.id, 
  u.email, 
  p.title AS post_title,
  COUNT(c.id) AS comment_count
FROM users u
LEFT JOIN posts p ON p.user_id = u.id
LEFT JOIN comments c ON c.post_id = p.id
WHERE u.id = $1
GROUP BY u.id, u.email, p.title;
"
            .to_string(),
            params: vec![QueryParam {
                index: 1,
                name: "id".to_string(),
                ts_type: "string".to_string(),
                is_optional: false,
            }],
            fields: vec![
                QueryField {
                    name: "id".to_string(),
                    ts_type: "string".to_string(),
                },
                QueryField {
                    name: "email".to_string(),
                    ts_type: "string".to_string(),
                },
                QueryField {
                    name: "post_title".to_string(),
                    ts_type: "string | null".to_string(),
                },
                QueryField {
                    name: "comment_count".to_string(),
                    ts_type: "number".to_string(),
                },
            ],
        };

        let ts = generate_file_ts(&[query]);
        println!("{}", ts);

        assert!(ts.contains("// Autogenerated by sqltype. DO NOT EDIT."));
        assert!(ts.contains("export interface GetUserWithPostsParams {\n  id: string;\n}"));
        assert!(ts.contains(
            "export interface GetUserWithPostsRow {\n  id: string;\n  email: string;\n  post_title: string | null;\n  comment_count: number;\n}"
        ));
        assert!(ts.contains("export const getUserWithPostsSql = `"));
        assert!(ts.contains("export type GetUserWithPostsQuery = {"));
        assert!(ts.contains("  params: GetUserWithPostsParams;"));
        assert!(ts.contains("  row: GetUserWithPostsRow;"));
    }

    #[test]
    fn test_empty_params() {
        let query = AnalyzedQuery {
            name: "GetAllUsers".to_string(),
            raw_sql: "SELECT id FROM users;".to_string(),
            params: vec![],
            fields: vec![QueryField {
                name: "id".to_string(),
                ts_type: "string".to_string(),
            }],
        };
        let ts = generate_file_ts(&[query]);
        assert!(ts.contains("export interface GetAllUsersParams {\n}"));
    }

    #[test]
    fn test_optional_param_codegen() {
        let mut catalog = crate::catalog::Catalog::default();
        catalog
            .apply_sql("
                CREATE TABLE users (
                    id UUID PRIMARY KEY,
                    name TEXT NOT NULL
                );
            ")
            .unwrap();

        let query_sql = "
            SELECT id, name FROM users WHERE ($1::text IS NULL OR name = $1) AND id = $2;
        ";
        let analyzed = crate::analyzer::analyze_query(query_sql, &catalog, Some("get_users_by_filter.sql")).unwrap();
        let ts = generate_file_ts(&[analyzed]);

        assert!(ts.contains("export interface GetUsersByFilterParams {\n  name?: string | null;\n  id: string;\n}"));
    }

    #[test]
    fn test_driver_profiles_codegen() {
        use crate::catalog::{Catalog, DriverTarget};

        let ddl = "
            CREATE TABLE data_records (
                id BIGINT PRIMARY KEY,
                payload BYTEA NOT NULL,
                active_date DATE NOT NULL,
                created_at TIMESTAMPTZ NOT NULL
            );
        ";

        // Bun driver
        let mut bun_catalog = Catalog::new(DriverTarget::Bun);
        bun_catalog.apply_sql(ddl).unwrap();
        let bun_query = crate::analyzer::analyze_query(
            "SELECT id, payload, active_date, created_at FROM data_records;",
            &bun_catalog,
            Some("get_records.sql"),
        )
        .unwrap();
        let bun_ts = generate_file_ts(&[bun_query]);
        assert!(bun_ts.contains("id: bigint;"));
        assert!(bun_ts.contains("payload: Uint8Array;"));
        assert!(bun_ts.contains("active_date: string;"));
        assert!(bun_ts.contains("created_at: Date;"));

        // Postgres / pg driver
        let mut pg_catalog = Catalog::new(DriverTarget::Postgres);
        pg_catalog.apply_sql(ddl).unwrap();
        let pg_query = crate::analyzer::analyze_query(
            "SELECT id, payload, active_date, created_at FROM data_records;",
            &pg_catalog,
            Some("get_records.sql"),
        )
        .unwrap();
        let pg_ts = generate_file_ts(&[pg_query]);
        assert!(pg_ts.contains("id: string;"));
        assert!(pg_ts.contains("payload: Buffer;"));
        assert!(pg_ts.contains("active_date: string;"));
        assert!(pg_ts.contains("created_at: Date;"));
    }
}
